version: '3'

services:
  services:
    client:
        build: ./client
        ports:
            - 8080:3000
        volumes: 
            - ./client/src:/app/src
    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes: 
            - ./server/src:/server/src 
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
volumes:
  web-client-build: