services:
    client:
        build: ./client
        command: sh -c "npm run build"
        volumes:
            - web-client-build:/app/build
    server:
        build: ./server
        command: sh -c "npm run prod"
    mongodb:
        image: mongo:4.4.9
    nginx:
        image: nginx:1.21.3
        depends_on:
            - server
            - client
        restart: always
        ports:
            - ${GATEWAY_PORT}:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - web-client-build:/web-client-build
volumes:
    web-client-build:
